# Generated by Django 5.1.3 on 2024-11-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artisan',
            options={'ordering': ['-created_at']},
        ),
    ]
